server:
  port: 8086
spring:
  application:
    name: gateway #服务名
  cloud:
    gateway:
      routes:
        - id: user-service #路由的ID
          uri: lb://user-service #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user/{id}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/